// <auto-generated />
using System;
using Day02.Employee.MVC.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Day02.Employee.MVC.Core.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20210702030731_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Day02.Employee.MVC.Core.Infrastructure.EmployeeEntity", b =>
                {
                    b.Property<int>("EmployeeCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("JobProfileId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<ulong>("Status")
                        .HasColumnType("bit(1)");

                    b.HasKey("EmployeeCode");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Day02.Employee.MVC.Core.Infrastructure.JobProfileEntity", b =>
                {
                    b.Property<int>("JobProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("JobProfileName")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("JobProfileId");

                    b.ToTable("jobprofile");
                });
#pragma warning restore 612, 618
        }
    }
}
